var map2 = L.map('mapanampula').setView([-18.85, 36.32], 6);

	var tiles = L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 20,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox/streets-v11',
		tileSize: 512,
		zoomOffset: -1
	}).addTo(map2);


       


$.ajax('http://cavateco.terrafirma.co.mz:8090/geoserver/ows',{
  type: 'GET',
  data: {
    service: 'WFS',
    version: '1.1.0',
    request: 'GetFeature',
    typename: 'cavateco_gras_nampula:povoados',
    //CQL_FILTER: "column='demo'",
    srsname: 'EPSG:4326',
    outputFormat: 'text/javascript',
    },
  dataType: 'jsonp',
  jsonpCallback:'callback:handleJson2',
  jsonp:'format_options'
 });
  //Geojson style file
  var myStyle = {
    'color': 'red'
  }
 
// the ajax callback function
var niessa=document.querySelector('#niessa');
var poiane=document.querySelector('#poiane');
var namuli=document.querySelector('#namuli');
var junho=document.querySelector('#junho');
var namicopo=document.querySelector('#namicopo');
var curapine=document.querySelector('#curapine');
var muhala=document.querySelector('#muhala');
var naihava=document.querySelector('#naihava');
var namihasse=document.querySelector('#namihasse');
var mutekereque=document.querySelector('#mutekereque');
var mesa=document.querySelector('#mesa');
var chica=document.querySelector('#chica');
var naculue=document.querySelector('#naculue');
var namalili=document.querySelector('#namalili');
var pajara=document.querySelector('#pajara');
var unidade=document.querySelector('#unidade');
var nanrele=document.querySelector('#nanrele');
var mutepa=document.querySelector('#mutepa');
var marrocane=document.querySelector('#marrocane');
var namacula=document.querySelector('#namacula');
var napipine=document.querySelector('#napipine');
var intatapila=document.querySelector('#intatapila');
var mutenapo=document.querySelector('#mutenapo');
var nametil=document.querySelector('#nametil');
var nacuacuali=document.querySelector('#nacuacuali');
var nathove=document.querySelector('#nathove');
var malate=document.querySelector('#malate');
var monapo=document.querySelector('#monapo');
var mavoto=document.querySelector('#mavoto');
var mueteia=document.querySelector('#mueteia');
var malapa=document.querySelector('#malapa');
var cuirini=document.querySelector('#cuirini');
var palaco=document.querySelector('#palaco');
function handleJson2(data2) {
    selectedArea2 = L.geoJson(data2, {
      style: myStyle,
      onEachFeature: function(feature, layer) {

        layer.bindPopup(`Name da Comunidade: ${feature.properties.name}`)
       
        
        feature.properties.name
 feature.properties.name
        layer.addEventListener("click", () => {

          if (feature.properties.name == "Comunidade de Niessa") {
            
           
            niessa.style.display='block'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Poiane") {
            
           
            niessa.style.display='none'
            poiane.style.display='block'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Namuali") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='block'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "25 de Junho") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='block'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Namicopo") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='block'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Curapine") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='block'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Muhala") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='block'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Naihava") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='block'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Namihasse") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='block'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Mutekereque") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='block'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Mesa") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='block'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Comunidade de chicá") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='block'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            mueteia.style.display='none'
          }
          if (feature.properties.name == "Naculue") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='block'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Namalili") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='block'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Pajara") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='block'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Unidade Moçambique") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='block'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Nanrele") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='block'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Mutepa") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='block'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Marrocane") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='block'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Namacula") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='block'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            palaco.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
          }
          if (feature.properties.name == "Napipine") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='block'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'   
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Intatapila Sede") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='block'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Mutenapo") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='block'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Nametil") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='block'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Nacuacuali") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='block'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            
            palaco.style.display='none'
          }
          if (feature.properties.name == "Nathove") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='block'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Malate") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='block'
            monapo.style.display='none'
            mavoto.style.display='none'
            
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Monapo") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='block'
            mavoto.style.display='none'
           
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Mavoto") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='block'
           
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Mueteia") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='block'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='none'
            
          }
          if (feature.properties.name == "Cuirini") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='block'
            malapa.style.display='none'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Malapa") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='block'
            palaco.style.display='none'
          }
          if (feature.properties.name == "Palaço") {
            
           
            niessa.style.display='none'
            poiane.style.display='none'
            namuli.style.display='none'
            junho.style.display='none'
            namicopo.style.display='none'
            curapine.style.display='none'
            muhala.style.display='none'
            naihava.style.display='none'
            namihasse.style.display='none'
            mutekereque.style.display='none'
            mesa.style.display='none'
            chica.style.display='none'
            naculue.style.display='none'
            namalili.style.display='none'
            pajara.style.display='none'
            unidade.style.display='none'
            nanrele.style.display='none'
            mutepa.style.display='none'
            marrocane.style.display='none'
            namacula.style.display='none'
            napipine.style.display='none'
            intatapila.style.display='none'
            mutenapo.style.display='none'
            nametil.style.display='none'
            nacuacuali.style.display='none'
            nathove.style.display='none'
            malate.style.display='none'
            monapo.style.display='none'
            mavoto.style.display='none'
            mueteia.style.display='none'
            cuirini.style.display='none'
            malapa.style.display='none'
            palaco.style.display='block'
          }
          
        })
      
      } 
    }).addTo(map2);
  map2.fitBounds(selectedArea2.getBounds());
}

